<a href="https://colab.research.google.com/github/vaishuankulage-maker/PDS-Assignment/blob/main/PracticalNo3_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name : Vaishnavi Ankulage

Branch : AI(AI&DS)

Class : Second Year

Div : A

Roll No: 03

                  Practical No : 03

Aim : Data Wrangling with pandas: Manipulate and transform data to suit the analysis needs.

Theory :

### 1. What is data wrangling, and why is it important before analysis?

**Data Wrangling** (also known as data cleaning, data preparation, or data munching) is the process of transforming and mapping data from a 'raw' data format into another format with the intent of making it more appropriate and valuable for a variety of downstream purposes, such as analysis, visualization, or machine learning.

**Importance before analysis:**

*   **Ensures Data Quality:** Raw data often contains errors, inconsistencies, and missing values. Wrangling addresses these issues, leading to more accurate and reliable analysis results.
*   **Enhances Data Usability:** It converts data into a structured and consistent format that is easier for analytical tools and algorithms to process.
*   **Improves Model Performance:** For machine learning, clean and well-prepared data is crucial for building robust and accurate models. Garbage in, garbage out.
*   **Facilitates Better Insights:** By resolving data issues, analysts can gain clearer and more meaningful insights, as anomalies or misleading patterns caused by dirty data are removed.
*   **Saves Time in the Long Run:** Although data wrangling can be time-consuming initially (often 60-80% of an analyst's time), it prevents errors and rework later in the analysis pipeline.

### 2. You receive messy data with missing values, duplicates, and wrong types. What steps will you follow to clean it?

When faced with messy data containing missing values, duplicates, and incorrect types, I would follow these general steps:

1.  **Understand the Data:** Begin by loading the data and getting a high-level overview. Use `df.head()`, `df.info()`, and `df.describe()` to understand its structure, column names, data types, and initial statistics.

2.  **Handle Missing Values:**
    *   **Identify:** Use `df.isnull().sum()` to count missing values per column and `df.isnull().sum() / len(df) * 100` to see their percentages. Visualizations like heatmaps can also help.
    *   **Decide Strategy:**
        *   **Impute:** Fill missing values with a statistical measure (mean, median, mode), a constant value, or use more advanced imputation techniques (e.g., K-Nearest Neighbors imputation, regression imputation). This is suitable for numerical data.
        *   **Forward/Backward Fill:** For time-series data, `ffill()` or `bfill()` can be used.
        *   **Remove:** If a column has a very high percentage of missing values or if the rows with missing values are few and represent a small portion of the dataset, remove the column (`df.drop()`) or the rows (`df.dropna()`).

3.  **Address Duplicate Data:**
    *   **Identify:** Use `df.duplicated().sum()` to count duplicate rows. `df[df.duplicated()]` shows the duplicate rows.
    *   **Remove:** Use `df.drop_duplicates()` to remove them. Decide whether to keep the first or last occurrence of a duplicate record.

4.  **Correct Data Types:**
    *   **Identify:** `df.dtypes` shows current data types. Incorrect types often occur when numbers are stored as strings or dates as objects.
    *   **Convert:** Use `df['column'].astype()` for simple conversions (e.g., `int`, `float`, `bool`). For dates, use `pd.to_datetime(df['column'], errors='coerce')` to handle unparseable dates gracefully. For categorical strings, convert to `category` dtype for memory efficiency.

5.  **Handle Inconsistent Data / Formatting:**
    *   **Text Data:** Convert text to a consistent case (lowercase/uppercase), remove leading/trailing spaces (`.str.strip()`), and standardize variations of the same entry (e.g., 'NY', 'N.Y.', 'New York' to 'New York'). Regular expressions can be useful here.
    *   **Numerical Data:** Check for values that fall outside expected ranges (e.g., negative ages, prices that are too high/low).

6.  **Outlier Detection and Treatment (Optional but Recommended):**
    *   **Identify:** Use visualizations like box plots, scatter plots, or statistical methods like Z-scores or IQR (Interquartile Range) to find outliers.
    *   **Decide Strategy:** Depending on the context, outliers might be: removed, transformed (e.g., log transformation), or capped (Winsorization).

7.  **Data Validation:** After cleaning, re-check `df.info()`, `df.describe()`, and `df.isnull().sum()` to ensure that the cleaning steps have had the desired effect and haven't introduced new issues. Perform sanity checks against business rules or common sense.

### 3. How can you check column names, data types, and summary statistics? What does `info()` show that `describe()` does not?

Here's how to check column names, data types, and summary statistics in pandas:

*   **Column Names:** Use `df.columns` to get an Index object containing all column names. You can convert it to a list using `df.columns.tolist()`.

*   **Data Types:** Use `df.dtypes` to get a Series showing the data type of each column. `df.info()` also provides this information along with other details.

*   **Summary Statistics:**
    *   For **numerical columns**, use `df.describe()`. This provides count, mean, standard deviation, min, max, and quartile values (25th, 50th/median, 75th percentiles).
    *   For **object (string) or categorical columns**, you can include them in `describe()` by passing `include='object'` or `include='category'`, which will show count, unique values, top occurring value, and its frequency.
    *   For **all columns**, `df.describe(include='all')` will show summary statistics for both numerical and object columns, using `NaN` for stats that don't apply.

#### What does `info()` show that `describe()` does not?

`df.info()` provides a concise summary of a DataFrame, including:

1.  **Index type and entries:** Information about the DataFrame's index (e.g., `RangeIndex: 891 entries, 0 to 890`).
2.  **Column names:** A list of all column names.
3.  **Non-null counts:** For each column, it shows the number of non-null (non-missing) entries. This is extremely useful for quickly identifying columns with missing values and the extent of their missingness.
4.  **Data type (Dtype):** The data type of each column (e.g., `int64`, `float64`, `object`, `datetime64`).
5.  **Memory usage:** The total memory usage of the DataFrame in bytes. This is very important for performance and resource management, especially with large datasets.
6.  **Number of columns by Dtype:** A summary count of columns for each data type (e.g., `float64(2), int64(5), object(5)`).

`df.describe()`, on the other hand, focuses purely on **statistical summaries** of the data within the columns. It does not provide non-null counts, memory usage, or general DataFrame structure information beyond the column types it can summarize.

### 4. How do you identify missing values and outliers in a dataset?

#### Identifying Missing Values:

Missing values are common in real-world datasets and can significantly impact analysis if not handled properly. Here are several ways to identify them in pandas:

1.  **`.isnull()` or `.isna()`:** These methods return a boolean DataFrame of the same shape as the original, indicating `True` where a value is missing (`NaN`, `None`, or `NaT` for datetime) and `False` otherwise.
    *   `df.isnull()`

2.  **`.sum()` after `.isnull()`:** To get a count of missing values per column, chain `.sum()`:
    *   `df.isnull().sum()`: Shows the total number of missing values for each column.
    *   `df.isnull().sum().sum()`: Gives the total number of missing values in the entire DataFrame.

3.  **Percentage of Missing Values:** To understand the proportion of missing data, divide the sum by the total number of rows:
    *   `df.isnull().sum() / len(df) * 100`: Shows the percentage of missing values per column.

4.  **Visualizations:**
    *   **Heatmap (using Seaborn):** A heatmap of `df.isnull()` can visually highlight patterns of missingness across columns and rows.
        ```python
        import seaborn as sns
        import matplotlib.pyplot as plt
        sns.heatmap(df.isnull(), cbar=False)
        plt.show()
        ```
    *   **`missingno` library:** This dedicated library provides various sophisticated visualizations for missing data, like bar charts, matrix plots, and dendrograms.

5.  **Specific Rows with Missing Values:** To inspect the actual rows that contain missing data in a specific column:
    *   `df[df['column_name'].isnull()]`

#### Identifying Outliers:

Outliers are data points that significantly deviate from other observations. They can be errors or genuine extreme values. Identifying them is crucial as they can skew statistical measures and model training. Here are common methods:

1.  **Visualizations:**
    *   **Box Plots:** A box plot (box-and-whisker plot) is excellent for visualizing the distribution of numerical data and clearly showing outliers as individual points beyond the whiskers. Outliers are typically defined as values that fall below Q1 - 1.5 * IQR or above Q3 + 1.5 * IQR.
        ```python
        sns.boxplot(x=df['numerical_column'])
        plt.show()
        ```
    *   **Scatter Plots:** For two numerical variables, scatter plots can reveal outliers that are far away from the main cluster of data points.
        ```python
        plt.scatter(df['col1'], df['col2'])
        plt.show()
        ```
    *   **Histograms/KDE Plots:** These can show if there are values far from the main distribution, often appearing as small, isolated peaks or long tails.

2.  **Statistical Methods:**
    *   **Z-score:** The Z-score measures how many standard deviations an element is from the mean. A common threshold for identifying outliers is a Z-score of ±3 or more.
        ```python
        from scipy.stats import zscore
        df['zscore_col'] = zscore(df['numerical_column'])
        outliers = df[(df['zscore_col'] > 3) | (df['zscore_col'] < -3)]
        ```
    *   **Interquartile Range (IQR) Method:** This is robust to skewed distributions. Values outside the range `[Q1 - 1.5*IQR, Q3 + 1.5*IQR]` are considered outliers.
        ```python
        Q1 = df['numerical_column'].quantile(0.25)
        Q3 = df['numerical_column'].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        outliers_iqr = df[(df['numerical_column'] < lower_bound) | (df['numerical_column'] > upper_bound)]
        ```

3.  **Machine Learning Methods (for multivariate outliers):**
    *   **Isolation Forest:** An unsupervised algorithm that works well for high-dimensional data.
    *   **Local Outlier Factor (LOF):** Measures the local deviation of density of a given data point with respect to its neighbors.
    *   **One-Class SVM:** Can be used for novelty detection (detecting outliers in new data) or outlier detection (detecting outliers in the training data).

The choice of method depends on the nature of the data, the distribution, and the definition of an outlier in the specific domain.

### 5. How do you reduce memory usage in pandas DataFrames?

Reducing memory usage in pandas DataFrames is crucial, especially when dealing with large datasets that might exceed available RAM or slow down computations. Here's a long theory explaining various techniques:

**1. Choosing Appropriate Data Types (`dtypes`):**

Pandas often infers generic `dtypes` when loading data (e.g., `int64`, `float64`, `object`), which might be overkill for the actual range of values or nature of the data. Explicitly defining or downcasting `dtypes` can lead to significant memory savings.

*   **Integer Types:** By default, pandas might assign `int64` for integers. If a column only contains values between -128 and 127, it can be downcasted to `int8`, saving 7 out of 8 bytes per entry. Similarly, `int16`, `int32`, `uint8`, `uint16`, `uint32`, `uint64` can be used. For example, an `id` column with values up to 65,000 can be `uint16` instead of `int64`.
    ```python
    df['small_int_col'] = df['small_int_col'].astype('int8')
    ```

*   **Float Types:** `float64` is the default. If precision is not a major concern, `float32` (single-precision) can halve the memory usage compared to `float64` (double-precision). For example, temperature readings might not need double precision.
    ```python
    df['price_col'] = df['price_col'].astype('float32')
    ```

*   **Boolean Types:** If a column only contains `True`/`False` values, ensure it's `bool` type. Pandas sometimes infers `int64` (0s and 1s) or `object` for boolean-like strings, which uses much more memory.
    ```python
    df['is_active'] = df['is_active'].astype('bool')
    ```

*   **Datetime Types:** `datetime64[ns]` is memory-efficient for dates and times, but it's important that strings are correctly parsed into this format. If only dates are needed, `datetime64[D]` (day precision) can sometimes save memory if the underlying engine supports it (though `datetime64[ns]` is most common and efficient for general use).
    ```python
    df['date_col'] = pd.to_datetime(df['date_col'])
    ```

**2. Using the `Categorical` Data Type for Strings:**

This is one of the most powerful memory-saving techniques for DataFrames with string columns. If a string column has a limited number of unique values (low cardinality) compared to the total number of rows, converting it to the `category` dtype can drastically reduce memory usage.

*   **How it works:** Instead of storing each string repeatedly, pandas stores a single copy of each unique string and then stores integer pointers (codes) to these unique strings for each row. This is similar to how factor variables are stored in R.
    ```python
    df['country'] = df['country'].astype('category')
    ```

*   **Benefits:** Besides memory efficiency, categorical data can also speed up certain operations like grouping, sorting, and filtering.

*   **Considerations:** If a string column has very high cardinality (many unique values), converting to `category` might not offer significant memory savings and could even increase memory usage if the unique string pool itself is very large. Also, operations that involve modifying categories (e.g., adding new categories frequently) can be slower.

**3. Efficient Loading with `pd.read_csv()` Parameters:**

When loading data, you can specify `dtypes` upfront, which prevents pandas from inferring and potentially using generic, memory-intensive types.

*   **`dtype` parameter:** Provide a dictionary mapping column names to their desired data types.
    ```python
    dtype_spec = {
        'id': 'uint16',
        'amount': 'float32',
        'status': 'category'
    }
    df = pd.read_csv('large_data.csv', dtype=dtype_spec)
    ```

*   **`usecols` parameter:** Load only the columns you actually need. This reduces the overall size of the DataFrame from the start.
    ```python
    df = pd.read_csv('large_data.csv', usecols=['id', 'amount', 'status'])
    ```

*   **`parse_dates` and `infer_datetime_format`:** Efficiently parse date columns directly during loading.
    ```python
    df = pd.read_csv('large_data.csv', parse_dates=['transaction_date'], infer_datetime_format=True)
    ```

**4. Deleting Unnecessary Columns:**

If certain columns are not required for your analysis, simply drop them. This is a straightforward way to reduce memory.

```python
df = df.drop(columns=['column_to_drop1', 'column_to_drop2'])
```

**5. Using Sparse Data Structures:**

For DataFrames where many values are `NaN` (or zeros, depending on the context), pandas offers `SparseDtype` for memory optimization. This stores only the non-null values and their locations, which can be highly efficient for very sparse data.

```python
# Convert a column to sparse
sparse_column = pd.arrays.SparseArray(df['sparse_col'])
df['sparse_col'] = sparse_column
# Or directly via astype
df['sparse_col'] = df['sparse_col'].astype(pd.SparseDtype("int", 0)) # for integer data with fill_value 0
```

**6. Processing Data in Chunks:**

If a dataset is too large to fit into memory entirely, you can load and process it in chunks using the `chunksize` parameter in `pd.read_csv()`. This allows you to perform operations on smaller parts of the data sequentially, reducing peak memory usage.

```python
chunks = pd.read_csv('very_large_data.csv', chunksize=100000)
processed_chunks = []
for chunk in chunks:
    # Perform operations on each chunk
    chunk['new_col'] = chunk['old_col'] * 2
    processed_chunks.append(chunk)
final_df = pd.concat(processed_chunks)
```

**7. Using `inplace=True` with Caution:**

Many pandas methods (like `drop`, `fillna`, `astype`) have an `inplace=True` argument. Using `inplace=True` modifies the DataFrame directly without creating a copy, which can save memory. However, it can also make debugging harder as it doesn't return a new DataFrame. It's often safer and clearer to reassign the result (`df = df.drop(...)`) unless memory is extremely constrained and you fully understand the implications.

**8. Garbage Collection:**

After dropping columns or creating temporary DataFrames, Python's garbage collector might not immediately free up the memory. Explicitly calling `gc.collect()` can sometimes force memory release, especially in interactive environments like Jupyter notebooks.

```python
import gc
# ... perform some memory-intensive operations and drop objects ...
del old_df # Dereference the old DataFrame
gc.collect()
```

By systematically applying these techniques, data scientists and analysts can significantly optimize memory usage in pandas, enabling them to work with larger datasets more efficiently and avoid out-of-memory errors.

## Data Wrangling with Pandas: Practical Exercises

In [ ]:
import pandas as pd
import numpy as np

# Create a sample DataFrame for demonstrations
data = {
    'Student_ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivan', 'Judy', 'Kelly', 'Liam'],
    'Branch': ['CS', 'IT', 'CS', 'AI', 'IT', 'CS', 'AI', 'IT', 'CS', 'AI', 'IT', 'CS'],
    'Score_Math': [85, 90, 78, 92, 88, 75, 95, 81, 89, 70, 80, 87],
    'Score_Science': [79, 85, 80, 90, 82, 70, 93, 78, 86, 68, 75, 81],
    'City': ['NY', 'LA', 'NY', 'SF', 'LA', 'NY', 'SF', 'LA', 'NY', 'SF', 'LA', 'NY'],
    'Enrollment_Date': ['2022-09-01', '2022-09-05', '2022-09-01', '2022-09-10', '2022-09-05', '2022-09-01', '2022-09-10', '2022-09-05', '2022-09-01', '2022-09-10', '2022-09-05', '2022-09-01']
}
df = pd.DataFrame(data)
display(df.head())

   Student_ID     Name Branch  Score_Math  Score_Science City Enrollment_Date
0           1    Alice     CS          85             79   NY      2022-09-01
1           2      Bob     IT          90             85   LA      2022-09-05
2           3  Charlie     CS          78             80   NY      2022-09-01
3           4    David     AI          92             90   SF      2022-09-10
4           5      Eve     IT          88             82   LA      2022-09-05

### Weak Students (Basic)

#### 1. Select a single column from a DataFrame.

In [ ]:
# Select the 'Name' column
name_column = df['Name']
display(name_column.head())

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
Name: Name, dtype: object

#### 2. Add a new column with constant values.

In [ ]:
# Add a new column 'Year' with a constant value
df['Year'] = 2023
display(df.head())

,Student_ID,Name,Branch,Score_Math,Score_Science,City,Enrollment_Date,Year
0,1,Alice,CS,85,79,NY,2022-09-01,2023
1,2,Bob,IT,90,85,LA,2022-09-05,2023
2,3,Charlie,CS,78,80,NY,2022-09-01,2023
3,4,David,AI,92,90,SF,2022-09-10,2023
4,5,Eve,IT,88,82,LA,2022-09-05,2023

#### 3. Sort a DataFrame by one column.

In [ ]:
# Sort the DataFrame by 'Score_Math' in ascending order
df_sorted = df.sort_values(by='Score_Math', ascending=True)
display(df_sorted.head())

,Student_ID,Name,Branch,Score_Math,Score_Science,City,Enrollment_Date,Year
9,10,Judy,AI,70,68,SF,2022-09-10,2023
5,6,Frank,CS,75,70,NY,2022-09-01,2023
2,3,Charlie,CS,78,80,NY,2022-09-01,2023
10,11,Kelly,IT,80,75,LA,2022-09-05,2023
7,8,Heidi,IT,81,78,LA,2022-09-05,2023

#### 4. Rename DataFrame columns.

In [ ]:
# Rename 'Score_Math' to 'Mathematics_Score' and 'Score_Science' to 'Science_Score'
df_renamed = df.rename(columns={'Score_Math': 'Mathematics_Score', 'Score_Science': 'Science_Score'})
display(df_renamed.head())

,Student_ID,Name,Branch,Mathematics_Score,Science_Score,City,Enrollment_Date,Year
0,1,Alice,CS,85,79,NY,2022-09-01,2023
1,2,Bob,IT,90,85,LA,2022-09-05,2023
2,3,Charlie,CS,78,80,NY,2022-09-01,2023
3,4,David,AI,92,90,SF,2022-09-10,2023
4,5,Eve,IT,88,82,LA,2022-09-05,2023

#### 5. Display summary statistics using `describe()`.

In [ ]:
# Display summary statistics for numerical columns
display(df.describe())

       Student_ID  Score_Math  Score_Science    Year
count   12.000000   12.000000      12.000000    12.0
mean     6.500000   84.166667      80.583333  2023.0
std      3.605551    7.444746       7.415688     0.0
min      1.000000   70.000000      68.000000  2023.0
25%      3.750000   79.500000      77.250000  2023.0
50%      6.500000   86.000000      80.500000  2023.0
75%      9.250000   89.250000      85.250000  2023.0
max     12.000000   95.000000      93.000000  2023.0

### Normal Students (Moderate)

#### 6. Filter rows using multiple conditions.

In [ ]:
# Filter students with 'Branch' as 'CS' and 'Score_Math' greater than 80
filtered_df = df[(df['Branch'] == 'CS') & (df['Score_Math'] > 80)]
display(filtered_df)

,Student_ID,Name,Branch,Score_Math,Score_Science,City,Enrollment_Date,Year
0,1,Alice,CS,85,79,NY,2022-09-01,2023
8,9,Ivan,CS,89,86,NY,2022-09-01,2023
11,12,Liam,CS,87,81,NY,2022-09-01,2023

#### 7. Group data by a categorical column and calculate mean.

In [ ]:
# Group by 'Branch' and calculate the mean of 'Score_Math' and 'Score_Science'
grouped_mean = df.groupby('Branch')[['Score_Math', 'Score_Science']].mean()
display(grouped_mean)

        Score_Math  Score_Science
Branch
AI       85.666667      83.666667
CS       82.800000      79.200000
IT       84.750000      80.000000

#### 8. Merge two DataFrames on a common column.

In [ ]:
# Create another sample DataFrame
additional_data = {
    'Student_ID': [1, 2, 3, 13, 14],
    'Attendance_Rate': [0.95, 0.92, 0.98, 0.85, 0.90]
}
attendance_df = pd.DataFrame(additional_data)

# Merge df and attendance_df on 'Student_ID'
merged_df = pd.merge(df, attendance_df, on='Student_ID', how='left')
display(merged_df)

,Student_ID,Name,Branch,Score_Math,Score_Science,City,Enrollment_Date,Year,Attendance_Rate
0,1,Alice,CS,85,79,NY,2022-09-01,2023,0.95
1,2,Bob,IT,90,85,LA,2022-09-05,2023,0.92
2,3,Charlie,CS,78,80,NY,2022-09-01,2023,0.98
3,4,David,AI,92,90,SF,2022-09-10,2023,NaN
4,5,Eve,IT,88,82,LA,2022-09-05,2023,NaN
5,6,Frank,CS,75,70,NY,2022-09-01,2023,NaN
6,7,Grace,AI,95,93,SF,2022-09-10,2023,NaN
7,8,Heidi,IT,81,78,LA,2022-09-05,2023,NaN
8,9,Ivan,CS,89,86,NY,2022-09-01,2023,NaN
9,10,Judy,AI,70,68,SF,2022-09-10,2023,NaN
10,11,Kelly,IT,80,75,LA,2022-09-05,2023,NaN
11,12,Liam,CS,87,81,NY,2022-09-01,2023,NaN

#### 9. Drop rows and columns using pandas functions.

In [ ]:
# Drop the 'Year' column
df_dropped_col = df.drop(columns=['Year'])

# Drop rows where 'Branch' is 'IT' (demonstrative, using a condition to select rows to drop)
df_dropped_rows = df[df['Branch'] != 'IT']

display(df_dropped_col.head())
display(df_dropped_rows.head())

   Student_ID     Name Branch  Score_Math  Score_Science City Enrollment_Date
0           1    Alice     CS          85             79   NY      2022-09-01
1           2      Bob     IT          90             85   LA      2022-09-05
2           3  Charlie     CS          78             80   NY      2022-09-01
3           4    David     AI          92             90   SF      2022-09-10
4           5      Eve     IT          88             82   LA      2022-09-05

,Student_ID,Name,Branch,Score_Math,Score_Science,City,Enrollment_Date,Year
0,1,Alice,CS,85,79,NY,2022-09-01,2023
2,3,Charlie,CS,78,80,NY,2022-09-01,2023
3,4,David,AI,92,90,SF,2022-09-10,2023
5,6,Frank,CS,75,70,NY,2022-09-01,2023
6,7,Grace,AI,95,93,SF,2022-09-10,2023

#### 10. Apply a simple function to a column.

In [ ]:
# Apply a function to create a new column 'Total_Score'
df['Total_Score'] = df['Score_Math'] + df['Score_Science']

# Apply a lambda function to convert 'City' to uppercase
df['City_Upper'] = df['City'].apply(lambda x: x.upper())
display(df.head())

,Student_ID,Name,Branch,Score_Math,Score_Science,City,Enrollment_Date,Year,Total_Score,City_Upper
0,1,Alice,CS,85,79,NY,2022-09-01,2023,164,NY
1,2,Bob,IT,90,85,LA,2022-09-05,2023,175,LA
2,3,Charlie,CS,78,80,NY,2022-09-01,2023,158,NY
3,4,David,AI,92,90,SF,2022-09-10,2023,182,SF
4,5,Eve,IT,88,82,LA,2022-09-05,2023,170,LA

### Bright Students (Advanced)

#### 11. Perform pivot and melt operations on a dataset.

In [ ]:
# Pivot: Reshape data based on 'Branch' to show scores
pivoted_df = df.pivot_table(index='Student_ID', columns='Branch', values=['Score_Math', 'Score_Science'])
display(pivoted_df.head())

# Melt: Unpivot the score columns from wide to long format
melted_df = df.melt(id_vars=['Student_ID', 'Name', 'Branch'], value_vars=['Score_Math', 'Score_Science'],
                     var_name='Subject', value_name='Score')
display(melted_df.head())

           Score_Math             Score_Science
Branch             AI    CS    IT            AI    CS    IT
Student_ID
1                 NaN  85.0   NaN           NaN  79.0   NaN
2                 NaN   NaN  90.0           NaN   NaN  85.0
3                 NaN  78.0   NaN           NaN  80.0   NaN
4                92.0   NaN   NaN          90.0   NaN   NaN
5                 NaN   NaN  88.0           NaN   NaN  82.0

   Student_ID     Name Branch     Subject  Score
0           1    Alice     CS  Score_Math     85
1           2      Bob     IT  Score_Math     90
2           3  Charlie     CS  Score_Math     78
3           4    David     AI  Score_Math     92
4           5      Eve     IT  Score_Math     88

#### 12. Implement multilevel indexing.

In [ ]:
# Set 'Branch' and 'City' as a multilevel index
df_multi_index = df.set_index(['Branch', 'City'])
display(df_multi_index.head())

# Access data using multilevel index
display(df_multi_index.loc[('CS', 'NY')])

,,Student_ID,Name,Score_Math,Score_Science,Enrollment_Date,Year,Total_Score,City_Upper
Branch,City,,,,,,,,
CS,NY,1,Alice,85,79,2022-09-01,2023,164,NY
IT,LA,2,Bob,90,85,2022-09-05,2023,175,LA
CS,NY,3,Charlie,78,80,2022-09-01,2023,158,NY
AI,SF,4,David,92,90,2022-09-10,2023,182,SF
IT,LA,5,Eve,88,82,2022-09-05,2023,170,LA

/tmp/ipykernel_11702/556789598.py:6: PerformanceWarning: indexing past lexsort depth may impact performance.
  display(df_multi_index.loc[('CS', 'NY')])

             Student_ID     Name  Score_Math  Score_Science Enrollment_Date  \
Branch City
CS     NY             1    Alice          85             79      2022-09-01
       NY             3  Charlie          78             80      2022-09-01
       NY             6    Frank          75             70      2022-09-01
       NY             9     Ivan          89             86      2022-09-01
       NY            12     Liam          87             81      2022-09-01

             Year  Total_Score City_Upper
Branch City
CS     NY    2023          164         NY
       NY    2023          158         NY
       NY    2023          145         NY
       NY    2023          175         NY
       NY    2023          168         NY

#### 13. Compare merge v/s join operations.

In [ ]:
# Create two sample DataFrames
df1 = pd.DataFrame({'key': ['A', 'B', 'C', 'D'], 'value': np.random.randint(1, 10, 4)})
df2 = pd.DataFrame({'key': ['B', 'D', 'E', 'F'], 'value2': np.random.randint(10, 20, 4)})
display(df1)
display(df2)

# Merge operation (flexible, can merge on columns or index)
merged_df_compare = pd.merge(df1, df2, on='key', how='inner')
print("\n--- Merge Result (inner join on 'key') ---")
display(merged_df_compare)

# Join operation (defaults to joining on index)
df1_indexed = df1.set_index('key')
df2_indexed = df2.set_index('key')
joined_df_compare = df1_indexed.join(df2_indexed, how='inner')
print("\n--- Join Result (inner join on index) ---")
display(joined_df_compare)

# If you want to join on a column using .join, you need to set one as index
joined_on_column = df1.set_index('key').join(df2.set_index('key'), how='inner')
print("\n--- Join Result (on column after setting index) ---")
display(joined_on_column)

  key  value
0   A      9
1   B      6
2   C      5
3   D      8

  key  value2
0   B      16
1   D      14
2   E      13
3   F      12

--- Merge Result (inner join on 'key') ---

  key  value  value2
0   B      6      16
1   D      8      14

--- Join Result (inner join on index) ---

     value  value2
key
B        6      16
D        8      14

--- Join Result (on column after setting index) ---

     value  value2
key
B        6      16
D        8      14

#### 14. Create custom aggregation functions.

In [ ]:
# Define a custom aggregation function (e.g., range of scores)
def score_range(series):
    return series.max() - series.min()

# Group by 'Branch' and apply custom aggregation along with other functions
custom_agg_df = df.groupby('Branch').agg(
    Avg_Math=('Score_Math', 'mean'),
    Max_Science=('Score_Science', 'max'),
    Math_Score_Range=('Score_Math', score_range)
)
display(custom_agg_df)

         Avg_Math  Max_Science  Math_Score_Range
Branch
AI      85.666667           93                25
CS      82.800000           86                14
IT      84.750000           85                10

#### 15. Perform time series based data wrangling.

In [ ]:
# Convert 'Enrollment_Date' to datetime objects
df['Enrollment_Date'] = pd.to_datetime(df['Enrollment_Date'])
display(df.info())

# Set 'Enrollment_Date' as index for time series operations
df_time_series = df.set_index('Enrollment_Date')
display(df_time_series.head())

# Resample data (e.g., count enrollments per week)
# Note: With limited data, weekly resampling might not show much variety.
weekly_enrollments = df_time_series['Student_ID'].resample('W').count()
print("\n--- Weekly Enrollments ---")
display(weekly_enrollments)

# Calculate a rolling mean for 'Score_Math' (example, requires more data for meaningful result)
# For demonstration, let's sort by date first if not already and apply rolling
sorted_df_for_rolling = df.sort_values(by='Enrollment_Date').set_index('Enrollment_Date')
sorted_df_for_rolling['Rolling_Avg_Math_Score'] = sorted_df_for_rolling['Score_Math'].rolling('3D').mean()
print("\n--- Rolling Average Math Score (3-day window) ---")
display(sorted_df_for_rolling[['Score_Math', 'Rolling_Avg_Math_Score']].head(7))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Student_ID       12 non-null     int64
 1   Name             12 non-null     object
 2   Branch           12 non-null     object
 3   Score_Math       12 non-null     int64
 4   Score_Science    12 non-null     int64
 5   City             12 non-null     object
 6   Enrollment_Date  12 non-null     datetime64[ns]
 7   Year             12 non-null     int64
 8   Total_Score      12 non-null     int64
 9   City_Upper       12 non-null     object
dtypes: datetime64[ns](1), int64(5), object(4)
memory usage: 1.1+ KB

None

,Student_ID,Name,Branch,Score_Math,Score_Science,City,Year,Total_Score,City_Upper
Enrollment_Date,,,,,,,,,
2022-09-01,1,Alice,CS,85,79,NY,2023,164,NY
2022-09-05,2,Bob,IT,90,85,LA,2023,175,LA
2022-09-01,3,Charlie,CS,78,80,NY,2023,158,NY
2022-09-10,4,David,AI,92,90,SF,2023,182,SF
2022-09-05,5,Eve,IT,88,82,LA,2023,170,LA

--- Weekly Enrollments ---

Enrollment_Date
2022-09-04    5
2022-09-11    7
Freq: W-SUN, Name: Student_ID, dtype: int64

--- Rolling Average Math Score (3-day window) ---

                 Score_Math  Rolling_Avg_Math_Score
Enrollment_Date
2022-09-01               85               85.000000
2022-09-01               78               81.500000
2022-09-01               75               79.333333
2022-09-01               89               81.750000
2022-09-01               87               82.800000
2022-09-05               90               90.000000
2022-09-05               88               89.000000

## Conclusion

This notebook provides a comprehensive overview of data wrangling techniques using the pandas library in Python. We've explored essential steps from understanding basic DataFrame operations like selection and sorting, to more complex tasks such as filtering with multiple conditions, grouping and aggregation, merging and joining DataFrames, and performing pivot and melt operations. Furthermore, we've touched upon multilevel indexing and time series specific wrangling. The theoretical explanations combined with practical examples demonstrate how to effectively manipulate and transform raw data into a clean, structured, and usable format for analysis, visualization, and machine learning.

Effective data wrangling is a critical skill in data science, ensuring data quality and enabling deeper insights from your datasets.